CREATE SEQUENCE IF NOT EXISTS task_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255),
    title       VARCHAR(255),
    version     BIGINT,
    CONSTRAINT task_pkey PRIMARY KEY (id)
);